name = "image-gen-api"
main = "worker.js"
compatibility_date = "2024-04-05"

# define the variable, but set the actual value via command line for security
[vars]
# HF_TOKEN = "will_be_set_in_secrets"
